### ISSUE TITLE
[Important][stepper] skills : no suggestions

### ISSUE THREAD

**Issue by hjsonghjsong** [SFSU-MyCareerCoach/resume-gen-frontend#25]
== How to reproduce the bug ==

1)  Click the submit button  --> no suggestion. no output.  (refer to Attached image )
2)  After 1) step, click submit button again --> submit button rotates for ever (for 1 min)
3) Click "Back" button  --> It is suppposed to go to previous page. But it just stops the rotation of submit button. And shows empty text box. (refer to attached image2)

![SS2](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/3c5905d6-4eee-4780-9150-0f82d6b8f2a1)

**Comment by hjsonghjsong** [comment]
- Version :  
commit ccb6f8baf49df749bb5437e8bb8ee44d7892e1f9 (HEAD -> main, origin/main, origin/HEAD)   
Author: shubhe25p <shubhpachchigar@gmail.com>
Date:   Wed Aug 9 23:04:43 2023 -0700


-How to produce :   Input "JS" in the skills. and hit the "Submit button". 



-What happens. :  got
![SS4](https://github.com/SFSU-MyCareerCoach/resume-gen-frontend/assets/17757289/425bc57d-6202-4de3-985d-384505cd4292)
 following error
Uncaught runtime errors:
×
ERROR
Objects are not valid as a React child (found: object with keys {0, generatedContent}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/static/js/bundle.js:97493:13)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:98269:11)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:101196:32)
    at updateHostComponent (http://localhost:3000/static/js/bundle.js:101840:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:103285:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:88271:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:88315:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:88372:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:108246:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:107493:16)
ERROR
Objects are not valid as a React child (found: object with keys {0, generatedContent}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/static/js/bundle.js:97493:13)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:98269:11)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:101196:32)
    at updateHostComponent (http://localhost:3000/static/js/bundle.js:101840:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:103285:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:88271:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:88315:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:88372:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:108246:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:107493:16)
ERROR
Objects are not valid as a React child (found: object with keys {0, generatedContent}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/static/js/bundle.js:97493:13)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:98269:11)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:101196:32)
    at updateHostComponent (http://localhost:3000/static/js/bundle.js:101840:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:103285:18)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:108224:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:107493:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:107416:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:107389:11)
    at recoverFromConcurrentError (http://localhost:3000/static/js/bundle.js:106881:24)
ERROR
subscription.unsubscribe is not a function
TypeError: subscription.unsubscribe is not a function
    at http://localhost:3000/static/js/bundle.js:188:20
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:104396:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:104534:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:106215:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:106171:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:106093:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:106081:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:107904:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:107857:18)
    at http://localhost:3000/static/js/bundle.js:107672:13
ERROR
subscription.unsubscribe is not a function
TypeError: subscription.unsubscribe is not a function
    at http://localhost:3000/static/js/bundle.js:188:20
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:104396:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:104534:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:106215:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:106171:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:106093:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:106081:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:107904:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:107857:18)
    at http://localhost:3000/static/js/bundle.js:107672:13

**Comment by hjsonghjsong** [comment]
Reopen the issues

**Comment by Gravemind1142** [comment]
Resolved 6af145f2c94a64e95f6e8a46938be415bf15450a
